### ISSUE TITLE
The vignette is wrong about FL

### ISSUE THREAD

**Issue by rasmus87** [CWWhitney/ethnobotanyR#22]
FLs is calculated correctly, as in the cited paper. But it is stated wrongly in the vignette.
Where it states URs it should state FCs instead, as this is what you actually do.

It should also state that the values are multiplied by 100, both in the vignette and in the help file.

**Comment by CWWhitney** [comment]
Good catch. 
I implemented these suggestions.

**Comment by CWWhitney** [comment]
This issue has been solved.

**Comment by rasmus87** [comment]
Better, but the text is a bit wrong:

![image](https://user-images.githubusercontent.com/7794216/103901504-84cc6a80-50f9-11eb-800f-ded076733dd0.png)


**1st marking should be:**

> "...compared to how many use that plant."

**2nd marking should be:**

> "frequency of citation"

**Comment by CWWhitney** [comment]
Edited close to this suggestion. I made the first statement "compared to all uses of the plant for any purpose."
