### ISSUE TITLE
@CWWhitney, Thank you for the development of the package! Is it possible to change the colors? which function do you use to change the colors of the CIs-plot?

### ISSUE THREAD

**Issue by CWWhitney** [CWWhitney/ethnobotanyR#27]
@CWWhitney, Thank you for the development of the package! Is it possible to change the colors? which function do you use to change the colors of the CIs-plot?

_Originally posted by @KamilaBio in https://github.com/CWWhitney/ethnobotanyR/issues/21#issuecomment-841386409_

**Comment by CWWhitney** [comment]
We can add more ggplot options. 
Assuming that by CIs-plot you mean the Radial_plot. i.e.:
CIs_plot <- ethnobotanyR::Radial_plot(ethnobotanydata, ethnobotanyR::CIs)

**Comment by KamilaBio** [comment]
Thank you!

**Comment by CWWhitney** [comment]
So, I added a 'colors' argument to the radial and alluvial plot options.

Get the latest package version with:
devtools::install_github("CWWhitney/ethnobotanyR")

The default is rainbow colors from rainbow().
